### ISSUE TITLE
Validation refactor

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-statistics#36]
Refactor validation to validate one property at a time rather than all properties at a time

**Comment by HenryGeorgist** [comment]
if I had my preference we would implement validation using IRule and IProperty Rule from Base in my framework. 

https://github.com/HenryGeorgist/Framework/blob/master/Base/Interfaces/IRule.cs
https://github.com/HenryGeorgist/Framework/blob/master/Base/Interfaces/IPropertyRule.cs

if we do that, we could surrender up the rules from the statistics model into the view model, and then report errors seamlessly to the view.

**Comment by HenryGeorgist** [comment]
@Brennan1994 has been writing property rules in the viewmodel, but it would not be difficult to refactor those into model level validation rules.

**Comment by HenryGeorgist** [comment]
fixed with #55
