### ISSUE TITLE
Triangular truncation

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-statistics#44]
Do we need to handle truncation of a triangular distribution?

**Comment by rnugent3** [comment]
Uniform distribution?

**Comment by HenryGeorgist** [comment]
Uniform distribution doesnt make sense. Triangluar could, but not really...

**Comment by rnugent3** [comment]
I agree that neither make sense. where we have truncated uniform and truncated triangular I put in regular uniform and regular triangular for now

**Comment by HenryGeorgist** [comment]
cool! Though i would say, you could just delete them from the enums, and delete the cases

**Comment by rnugent3** [comment]
this is a logical bug, we want to remove triangular and uniform truncation.

**Comment by HenryGeorgist** [comment]
there are no current references to truncated uniform or triangular - none in enum, the distribution classes themselves, nor in the idistributionfactory.

i suggest we close this issue @rnugent3 what do you think?

**Comment by rnugent3** [comment]
I agree 

Best,

R Nugent III
