### ISSUE TITLE
Replace SampleStatistics

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-statistics#46]
Let's replace SampleStatistics with Will's code in go-statistics to do away with the last dependency on Math.NET

**Comment by rnugent3** [comment]
What methods are used? @HenryGeorgist sees Fit() as the only method used in the model, and only for the LP3.

**Comment by HenryGeorgist** [comment]
i didnt look through the code to determine what is using the methods or not - but rather, thought conceptually about why we would need "fit" the only time we would need it is as part of the bootstratp, which we could do in a number of ways.
Ideally, if we wanted to use "fit" as a means for bootstrap, we should have an isolated interface that manages that task or "IFittable" something like that which has a simple method public IDistribution fit(data double[])

**Comment by rnugent3** [comment]
Understood. I’d like to leave this issue in the backlog for now if that’s okay so we can focus on what doesn’t work or what doesn’t exist now, and later improve what already works.

**Comment by rnugent3** [comment]
@HenryGeorgist completed this issue.
