### ISSUE TITLE
Remove IData

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-statistics#49]
no unused classes that i am aware of - idata is one i would consider removing (along with data) but it is not necessary and it would have potential implications elsewhere.

_Originally posted by @HenryGeorgist in https://github.com/HydrologicEngineeringCenter/fda-statistics/issues/42#issuecomment-1010302098_

**Comment by HenryGeorgist** [comment]
fixed with #57
