### ISSUE TITLE
shouldnt lp3 have an exception for zero stdev?

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-statistics#53]
shouldnt lp3 have an exception for zero stdev? what are reasonable parameter values for an LP3? This is a question for a hydrologic engineer. 

_Originally posted by @HenryGeorgist in https://github.com/HydrologicEngineeringCenter/fda-statistics/pull/52#pullrequestreview-853408146_

**Comment by HenryGeorgist** [comment]
tag mike bartles.
