### ISSUE TITLE
histogram with observations of all the same value

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-statistics#63]
when you run a mean random number provider and put all the results in a histogram, some of the histogram methods are dysfunctional - e.g. inverse CDF. If we allow the user to run things without uncertainty, we'll run into issues.

**Comment by HenryGeorgist** [comment]
yeah. we shouldnt allow meanrandomprovider to have iterations be more than 1 i think. but the point still remains, if there is no variation in the values, should we handle that case.

I think we could query if sampleMin=sampleMax and hanlde that case (in inversecdf cdf and pdf?)

**Comment by rnugent3** [comment]
histogram things should work on 1 observation, right? I suppose that having 1 observation or 1000 observations of the same value would give us a similar histogram, with data in just one bin.

**Comment by HenryGeorgist** [comment]
i think so, any number of bins should work i think. we might check if _N = 0 also... if someone asks for cdf inverse cdf or pdf and no values are in the bin?
